flask_blog/main/routes.py
import flask_blog.controller as controller
from flask import flash, render_template, url_for, redirect
from flask import Blueprint
from flask_blog.controller import main_logger

main = Blueprint('main', __name__)


@main.route('/')
def welcome():
    if controller.check_if_user_is_authenticated():
        main_logger.warning('User tried to see landing page while logged in')
        return redirect(url_for('main.home')) 
    return render_template('main/landing_page.html')


@main.route('/home', methods=['GET'])
def home():
    if not controller.check_if_user_is_authenticated():
        flash('Please Register or Login to see posts!','danger')
        main_logger.warning('User tried to see posts without being authenticated!')
        return redirect(url_for('main.welcome')) 
    page,posts = controller.display_home_posts()
    return render_template('main/home.html', posts=posts, page=page)

@main.route('/about')
def about():
    return render_template('main/about.html', title='About')

flask_blog/posts/routes.py
import flask_blog.controller as controller
from flask import render_template, url_for, redirect, request
from flask_blog.posts.forms import PostForm
from flask_blog.models import Post
from flask_login import login_required
from flask import Blueprint



posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        controller.add_post(form)
        return redirect(url_for('main.home'))
    else:
        return render_template('posts/create_post.html', title='New Post', form=form, legend="New Post")



@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('posts/post.html', post=post)



@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post = controller.try_to_fetch_or_abort(post_id=post_id)
    form = PostForm()
    
    if form.validate_on_submit():
        controller.update_post(post=post, form=form)
        return redirect(url_for('main.home', post_id=post.id))
    
    elif request.method == 'GET':
        controller.fetch_post_data(form=form, post=post)
        
    return render_template('posts/create_post.html', 
                           title='Update Post', 
                           form=form,
                           legend='Update Post')
    
    
@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    controller.delete_post(post_id=post_id)
    return redirect(url_for('main.home'))

flask_blog/users/routes.py
import flask_blog.controller as controller
from flask import render_template, url_for, redirect, request
from flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flask_login import current_user, logout_user, login_required
from flask import Blueprint


users = Blueprint('users', __name__)

@users.route('/register', methods=['POST', 'GET'])
def register():
    if controller.check_if_user_is_authenticated():
        return redirect(url_for('main.home'))  
    form = RegistrationForm()
    res = controller.create_a_user_of_fail(form)
    if res:
        return redirect(url_for('main.welcome')) 
    else:
        return render_template('users/register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if controller.check_if_user_is_authenticated():
        return redirect(url_for('main.home'))
    form = LoginForm()
    next_page = controller.login_a_user_of_fail(form)
    if next_page:
        return redirect(url_for('main.home'))
    return render_template('users/login.html', title='Login', form=form)



@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("main.welcome"))

    

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    controller.edit_account(form)
    if request.method == "GET":
        controller.get_account(form)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('main/account.html', title='Login', image_file=image_file, form=form)
@users.route('/user/<string:username>')
def user_posts(username):
    page,user,posts = controller.fetch_users_posts(username=username)
    return render_template('users/user_posts.html', posts=posts, user=user,page=page)

flask_blog/templates/layouts/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Toodoo - {{ title }}</title>
    {% else %}
        <title>Toodoo</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Toodoo</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
      <div class="row">
        <div class="text-center col-md-12 col-sm-12 border-top border-dark mt-3">
                  <h6 class="text-uppercase fw-bold mb-4 mt-4">
                      <i class="fas fa-gem me-3"></i>TooDoo Blog App
                  </h6>
                <p>
              Let the first-ever blog Blow your Mind, one post at a time!
            </p>
            <div class="col item social"><a href="http://www.facebook.com"><i class="fa fa-facebook"></i></a><a href="http://www.twitter.com"><i class="fa fa-twitter"></i></a><a href="http://www.youtube.com"><i class="fa fa-youtube"></i></a><a href="http://www.instagram.com"><i class="fa fa-instagram"></i></a><a href="http://www.google.com"><i class="fa fa-google"></i></a></div>
        </div>
      </div>
      <div class="text-center p-4 mt-2" style="background-color: rgba(0, 0, 0, 0.05);">
      © TooDoo Careers:
      <a class="text-reset fw-bold" href="#">Careers</a>
      </div>
    </main>



    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flask_blog/templates/layouts/pagination_layout_main.html
<div class="col text-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

flask_blog/templates/layouts/pagination_layout_user.html
<div class="col text-center">
    {% for page_num in posts.iter_pages() %}
      {% if page_num %}
        {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{url_for('users.user_posts', username = user.username, page=page_num)}}">{{ page_num }}</a>      
        {% else %}
      <a class=" btn btn-outline-info mb-4" href="{{url_for('users.user_posts', username = user.username, page=page_num)}}">{{ page_num }}</a> 
      {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>

flask_blog/templates/layouts/post_layout.html
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      </div>
      <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content }}</p>
      {% if post.author == current_user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
      </div>
    {% endif %}
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
  </article>